project:
  type: website
  output-dir: docs

website:
  title: "Pham Dan Anh Nguyen"
  favicon: file/duck.png
  navbar:
    title: false 
    logo: file/duck.png
    logo-alt: "Anh loves ducks!"
    left:
      - href: index.qmd
        text: Home
      - href: pages/about.qmd
        text: About
      - href: file/cv.pdf
        text: CV
        target: _blank
      - href: pages/research.qmd
        text: Research
      - href: pages/pub.qmd
        text: Publications
      - href: pages/teaching.qmd
        text: Teaching
      - pages/posts.qmd

  page-footer:
    background: light
    left: Copyright 2025, Pham Dan Anh Nguyen
    right: Made by combining a lot of tutorials together
    
format:
  html:
    theme: litera
    css: styles.css
    toc: true
    page-layout: full